name: BuildPlugin
on:
    push:
        branches:
            - main

jobs:
    build:
        uses: FriendsOfShopware/workflows/.github/workflows/github.yml@main
        with:
            extensionName: FroshProductCompare
            shopwareVersion: 6.4.1
        secrets:
            ghToken: ${{ secrets.GITHUB_TOKEN }}
